import "./globals.css";
import "./fonts.css";
import { HeroUIProvider } from "@heroui/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{ direction: "rtl" }}
        className={` antialiased bg-white text-black  `}
      >
        <HeroUIProvider>{children}</HeroUIProvider>
      </body>
    </html>
  );
}
